### PR TITLE
[17.0][ADD] bookstore_mgmt_google_books_api: New module bookstore_mgmt_google_books_api

### PR DESCRIPTION
**Pull request by peluko00**
This module add the possibility to import book information from Google Books via API calls

cc https://github.com/APSL 163009
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall @BernatObrador @ppyczko please review

### CODE REVIEW

**Review by miquelpascual — APPROVED** [review]
LGTM, tested in runboat

**Review by BernatObrador — APPROVED** [review]
LGTM, testes in runboat and code review

**Review by ppyczko — APPROVED** [review]
LGTM! Code review and tested in runboat 👍

**Comment by miquelalzanillas** [comment]
Hi @peluko00 ,

Thanks. I think we still can improve some points.

**Book Synopsis**
In case of an e-commerce, the book synopsis will not be displayed in the product page because is only stored in an internal product field.

**Book Cover Image Size**
Can we check the image size synced from Google? Seems too small in an e-commerce published  product page. May can be bigger?

**Massive Sync**
I think it will be a need. But an action available from the book list view to select several records to sync would be very nice here.

**Review by miquelalzanillas — APPROVED** [review]

**Comment by peluko00** [comment]
Hi @pedrobaeza, sorry for ping you but this pr is ready and only needs a PSC to review it. Thanks!

**Pull request merged**
