### PR TITLE
Add bug tracker link on README.rst

### PR DESCRIPTION
**Pull request by yvaucher**
https://github.com/OCA/maintainer-tools/pull/59

### CODE REVIEW

**Comment by pedrobaeza** [comment]
spaces on body text are ignored. You should encode them on HTML.

**Comment by yvaucher** [comment]
Indeed :/

**Comment by yvaucher** [comment]
@pedrobaeza Thanks fixed

**Comment by pedrobaeza** [comment]
I insist that this is very laborious, but indeed is better.

:+1:

**Comment by tafaRU** [comment]
:+1:

**Pull request merged**
