### PR TITLE
[17.0][ADD] bookstore_mgmt: New module bookstore_mgmt

### PR DESCRIPTION
**Pull request by peluko00**
This application manages books as products, authors, editorials and genres.

cc https://github.com/APSL 163007
@miquelalzanillas @javierobcn @mpascuall @BernatObrador @ppyczko please review

### CODE REVIEW

**Review by BernatObrador — APPROVED** [review]
LGTM

**Review by ppyczko — APPROVED** [review]
LGTM, tested in runboat

**Comment by peluko00** [comment]
Can you review it @pedrobaeza when you have a moment please.
Thanks!

**Review by miquelpascual — APPROVED** [review]
LGTM, tested in runboat

**Comment by pedrobaeza** [comment]
Well, I can't review all your PRs, also because I may not know about the features.

Being a new module, and I trust that your team has done an honest review, let's merge it.

/ocabot merge nobump

**Comment by peluko00** [comment]
> Well, I can't review all your PRs, also because I may not know about the features.
> 
> Being a new module, and I trust that your team has done an honest review, let's merge it.
> 
> /ocabot merge nobump

Many thanks! It's possible to add me as PSC because i'm working in a new module for this repo?

**Comment by pedrobaeza** [comment]
Put you as maintainer of the module, and it requires less bureaucracy.

**Pull request merged**
